#!name = mihomo win 配置文件
#!date = 2025-03-20 17:30
#!source = https://wiki.metacubex.one/example/conf/#__tabbed_1_2

# 全局锚点配置
rule-anchor:
  # 机场订阅锚点
  pr: &pr {type: http, interval: 3600, health-check: {enable: true, url: "https://www.gstatic.com/generate_204", interval: 300}}
  # DNS锚点配置
  default: &default ['223.5.5.5', '119.29.29.29']
  direct: &direct ['https://223.5.5.5/dns-query', 'https://120.53.53.53/dns-query', 'https://dns.alidns.com/dns-query', 'https://doh.pub/dns-query']
  # 策略锚点配置
  pg: &pg {type: select, proxies: [默认, 自动, 香港, 日本, 美国, 狮城]}
  ps: &ps {type: select, proxies: [中国, 香港, 日本, 美国, 狮城]}
  mt: &mt {type: select, include-all: true}
  at: &at {type: url-test, include-all: true, tolerance: 10}
  lb: &lb {type: load-balance, include-all: true, tolerance: 10, strategy: consistent-hashing}
  # 节点锚点配置
  hk: &hk "(?i)港|hk|hongkong|hong kong"
  tw: &tw "(?i)台|tw|taiwan"
  jp: &jp "(?i)日本|jp|japan"
  us: &us "(?i)美|us|unitedstates|united states"
  sg: &sg "(?i)(新|sg|singapore)"
  al: &al "^((?!(中国|直连|拦截)).)*$"
  cn: &cn "中国"
  ad: &ad "拦截"
  # 规则锚点配置
  ipcidr: &ipcidr {type: http, interval: 21600, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 21600, behavior: domain, format: mrs}
  domain_text: &domain_text {type: http, interval: 21600, behavior: domain, format: text}

# 机场订阅配置
proxy-providers:
  provider1:
    <<: *pr
    url: "此处填写机场订阅"
    override:
      additional-prefix: "此处填写机场名字（可选）"
  provider2:
    <<: *pr
    url: "此处填写机场订阅"
    override:
      additional-prefix: "此处填写机场名字（可选）"

# 单独节点配置
proxies: 
  - {name: "拦截 01", type: reject}
  - {name: "中国 01", type: direct, udp: true}

##### 全局设置配置 #####
mixed-port: 7890
ipv6: true
allow-lan: true
unified-delay: true
tcp-concurrent: true

# ui 配置
external-ui: ui
external-controller: 0.0.0.0:9090
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

find-process-mode: strict
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"

# TUN 配置
tun:
  enable: true
  stack: mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

# DNS 配置
dns:
  enable: true
  ipv6: true
  prefer-h3: true
  enhanced-mode: fake-ip
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
    - "+.market.xiaomi.com"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
  default-nameserver: *default
  nameserver: *direct

# 策略分组配置
proxy-groups:
  # 策略组
  - {name: 默认, type: select, proxies: [自动, 香港, 日本, 美国, 狮城]}
  - {name: 海外, <<: *pg}
  - {name: 微软, <<: *pg}
  - {name: 奈飞, <<: *pg}
  - {name: 推特, <<: *pg}
  - {name: 谷歌, <<: *pg}
  - {name: 电报, <<: *pg}
  - {name: TikTok, <<: *pg}
  - {name: ChatGPT, <<: *pg}
  - {name: 游戏, <<: *ps}
  - {name: 苹果, <<: *ps}
  - {name: 直连, <<: *ps}
  # 节点筛选
  - {name: 自动, <<: *at, filter: *al}
  - {name: 香港, <<: *at, filter: *hk}
  - {name: 台湾, <<: *at, filter: *tw}
  - {name: 日本, <<: *at, filter: *jp}
  - {name: 美国, <<: *at, filter: *us}
  - {name: 狮城, <<: *at, filter: *sg}
  - {name: 中国, <<: *mt, filter: *cn}
  - {name: 广告, <<: *mt, filter: *ad}

# 策略规则配置
rules:
  # 本地/局域网 IP
  - RULE-SET,Local_ip,直连,no-resolve
  # 广告
  - RULE-SET,Ads_Block_domain,广告
  # OpenAI
  - RULE-SET,OpenAI_domain,ChatGPT
  # 电报
  - RULE-SET,Telegram_domain,电报
  # 游戏
  - RULE-SET,Epic_domain,游戏
  - RULE-SET,Steam_domain,游戏
  # 谷歌/油管
  - RULE-SET,YouTube_domain,谷歌
  - RULE-SET,Google_domain,谷歌
  # 微软
  - RULE-SET,GitHub_domain,微软
  - RULE-SET,OneDrive_domain,微软
  - RULE-SET,Microsoft_domain,微软
  # 社交/媒体
  - RULE-SET,TikTok_domain,TikTok
  - RULE-SET,Disney_domain,奈飞
  - RULE-SET,Netflix_domain,奈飞
  - RULE-SET,Spotify_domain,奈飞
  - RULE-SET,PayPal_domain,推特
  - RULE-SET,Twitter_domain,推特
  - RULE-SET,Facebook_domain,推特
  - RULE-SET,Instagram_domain,推特
  # 苹果
  - RULE-SET,Apple_domain,苹果
  # 国内
  - RULE-SET,Bilibili_domain,直连
  - RULE-SET,China_domain,直连
  # 海外
  - RULE-SET,Global_domain,海外
  # ipcidr
  - RULE-SET,Google_ip,谷歌
  - RULE-SET,Netflix_ip,奈飞
  - RULE-SET,Twitter_ip,推特
  - RULE-SET,Facebook_ip,推特
  - RULE-SET,Telegram_ip,电报
  - RULE-SET,China_ip,直连
  - MATCH,海外

# 规则订阅配置
rule-providers:
  # ChatGPT
  OpenAI_domain:
    <<: *domain
    url: https://github.com/thNylHx/Tools/raw/main/Ruleset/mihomo/geosite/Openai.mrs
  # 谷歌
  YouTube_domain:
    <<: *domain
    url: https://github.com/thNylHx/Tools/raw/main/Ruleset/mihomo/geosite/YouTube.mrs
  Google_domain:
    <<: *domain
    url: https://github.com/thNylHx/Tools/raw/main/Ruleset/mihomo/geosite/Google.mrs
  # 微软
  GitHub_domain:
    <<: *domain
    url: https://github.com/thNylHx/Tools/raw/main/Ruleset/mihomo/geosite/GitHub.mrs
  OneDrive_domain:
    <<: *domain
    url: https://github.com/thNylHx/Tools/raw/main/Ruleset/mihomo/geosite/OneDrive.mrs
  Microsoft_domain:
    <<: *domain
    url: https://github.com/thNylHx/Tools/raw/main/Ruleset/mihomo/geosite/Microsoft.mrs
  # 游戏
  Epic_domain:
    <<: *domain
    url: https://github.com/thNylHx/Tools/raw/main/Ruleset/mihomo/geosite/Epic.mrs
  Steam_domain:
    <<: *domain
    url: https://github.com/thNylHx/Tools/raw/main/Ruleset/mihomo/geosite/Steam.mrs
  # 社交
  Telegram_domain:
    <<: *domain
    url: https://github.com/thNylHx/Tools/raw/main/Ruleset/mihomo/geosite/Telegram.mrs
  Facebook_domain:
    <<: *domain
    url: https://github.com/thNylHx/Tools/raw/main/Ruleset/mihomo/geosite/Facebook.mrs
  Instagram_domain:
    <<: *domain
    url: https://github.com/thNylHx/Tools/raw/main/Ruleset/mihomo/geosite/Instagram.mrs
  PayPal_domain:
    <<: *domain
    url: https://github.com/thNylHx/Tools/raw/main/Ruleset/mihomo/geosite/PayPal.mrs
  Twitter_domain:
    <<: *domain
    url: https://github.com/thNylHx/Tools/raw/main/Ruleset/mihomo/geosite/Twitter.mrs
  # 影视
  Spotify_domain:
    <<: *domain
    url: https://github.com/thNylHx/Tools/raw/main/Ruleset/mihomo/geosite/Spotify.mrs
  Netflix_domain:
    <<: *domain
    url: https://github.com/thNylHx/Tools/raw/main/Ruleset/mihomo/geosite/Netflix.mrs
  Disney_domain:
    <<: *domain
    url: https://github.com/thNylHx/Tools/raw/main/Ruleset/mihomo/geosite/Disney.mrs
  TikTok_domain:
    <<: *domain
    url: https://github.com/thNylHx/Tools/raw/main/Ruleset/mihomo/geosite/Tiktok.mrs
  # 海外
  Global_domain:
    <<: *domain
    url: https://github.com/thNylHx/Tools/raw/main/Ruleset/mihomo/geosite/Global.mrs
  # 苹果
  Apple_domain:
    <<: *domain
    url: https://github.com/thNylHx/Tools/raw/main/Ruleset/mihomo/geosite/Apple.mrs
  # 国内
  Bilibili_domain:
    <<: *domain
    url: https://github.com/thNylHx/Tools/raw/main/Ruleset/mihomo/geosite/Bilibili.mrs
  China_domain:
    <<: *domain
    url: https://github.com/thNylHx/Tools/raw/main/Ruleset/mihomo/geosite/China.mrs

  # ipcidr
  China_ip:
    <<: *ipcidr
    url: https://github.com/thNylHx/Tools/raw/main/Ruleset/mihomo/geoip/China.mrs
  Local_ip:
    <<: *ipcidr
    url: https://github.com/thNylHx/Tools/raw/main/Ruleset/mihomo/geoip/Local.mrs
  Google_ip:
    <<: *ipcidr
    url: https://github.com/thNylHx/Tools/raw/main/Ruleset/mihomo/geoip/Google.mrs
  Twitter_ip:
    <<: *ipcidr
    url: https://github.com/thNylHx/Tools/raw/main/Ruleset/mihomo/geoip/Twitter.mrs
  Netflix_ip:
    <<: *ipcidr
    url: https://github.com/thNylHx/Tools/raw/main/Ruleset/mihomo/geoip/Netflix.mrs
  Telegram_ip:
    <<: *ipcidr
    url: https://github.com/thNylHx/Tools/raw/main/Ruleset/mihomo/geoip/Telegram.mrs
  Facebook_ip:
    <<: *ipcidr
    url: https://github.com/thNylHx/Tools/raw/main/Ruleset/mihomo/geoip/Facebook.mrs

  # 广告
  Ads_Block_domain:
    <<: *domain_text
    url: https://github.com/thNylHx/Tools/raw/main/Ruleset/mihomo/Block/Ads_Block.list